### ISSUE TITLE
Clarify factories (naming)

### ISSUE THREAD

**Issue by jessieay** [18F/micropurchase#1066]
frequently find myself visiting the factory file to understand what a factory is.  How can we clean up our naming so that we do not need to do that? Wonder if we are relying too heavily on traits....

**Comment by harrisj** [comment]
I personally like the ability to tweak my test auction via traits rather than knowing that a specific named factory also does this or that thing. But I think we have some redundant traits among other problems

**Comment by jessieay** [comment]
yeah I see that, traits are much more compact

I think maybe rather than having so many traits with several attributes, we should focus on traits with just one or two so we aren't accidentally getting records that have more specific details than we need.  eg

```
    trait :payment_needed do
      delivery_due_at_expired
      accepted
      delivered
      c2_approved
      not_paid
    end

```

I feel like this could be more concise.

**Comment by harrisj** [comment]
So, I think we decided that we should focus on a few small PRs to eliminate some redundant traits like `:running` and then see how we feel about it from there

**Comment by jessieay** [comment]
I also think that removing / refacotring any traits that call other traits would be very helpful as an initial step. even if that just means adding a bunch of explicit attributes to traits

**Comment by harrisj** [comment]
It seems like we have two cases where traits might call a bunch of other traits:

1. The traits are tightly coupled and it is an error condition to have trait A without trait B
2. The traits are usually together, so that a record with trait A will typically also have trait B

I think the second case are ones we should absolutely unroll to be more explicit where called, but I think for the first case, it might make more sense to keep the first case

**Comment by jessieay** [comment]
Some PRs for this (not to complete it)

https://github.com/18F/micropurchase/pull/1092
https://github.com/18F/micropurchase/pull/1093
