### ISSUE TITLE
Remove DUNS number validation flash message

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#1241]
So that I only see messages I need to see when i need to see them, as a vendor, I should only be reminded to supply a valid Duns number only when I am on the show page for an active auction and I'm qualified to bid

So basically, let's remove the DUNS number flash message for vendors on micropurchase.18f.gov

![screen shot 2016-11-07 at 3 15 20 pm](https://cloud.githubusercontent.com/assets/100149/20080163/fca16fb8-a4fc-11e6-9c11-b587e11abbb1.png)

**Comment by harrisj** [comment]
Okay, going to work on this. Technically, you'd not be qualified to bid if you see this flash, so I'd like to change the rules above so it only shows on available auction show pages

**Comment by harrisj** [comment]
So, do you want to remove all the SAM-related messages from the homepage? These are

- "Your DUNS number has been verified in Sam.gov"
- "Your profile is pending while your DUNS number is being validated. This typically takes less than one hour"
- "Your DUNS number was not found in Sam.gov. Please enter a valid DUNS number to complete your profile. Check https://www.sam.gov/portal/SAM to make sure your DUNS number is correct. If you need any help email us at micropurchase@gsa.gov"
- "In order to bid, you must supply a valid DUNS number. Please update your profile"

Specifically:
1. Can all of these messages be moved from the auctions index page to auction show page?
2. Should some of these messages be displayed even if the auction is not open?

**Comment by mtorres253** [comment]
Thanks @harrisj let me work on some stories to discuss today. There is already a message on the auction show page when a vendor doesn't have a valid DUNs. I think we want to move all the messaging off of the homepage to the vendor profile page and the auction show page for active auctions

**Comment by mtorres253** [comment]
Are you still working on this one @harrisj?
