### ISSUE TITLE
Fix time-related intermittenty failing test

### ISSUE THREAD

**Issue by jessieay** [18F/micropurchase#1318]
```
(::) failed steps (::)
expected to find text "Estimated delivery date October 12, 2016 01:00:00 PM EDT" in "Estimated delivery date October 11, 2016 01:00:00 PM EDT" (RSpec::Expectations::ExpectationNotMetError)
./features/step_definitions/admin_auction_form_steps.rb:89:in `block (2 levels) in <top (required)>'
./features/step_definitions/admin_auction_form_steps.rb:86:in `/^I should see the updated estimate for the delivery deadline$/'
features/admin_creates_auction.feature:31:in `Then I should see the updated estimate for the delivery deadline'
Failing Scenarios:
cucumber features/admin_creates_auction.feature:22 # Scenario: Adding an auction with a non-default delivery timeline
```

 https://travis-ci.org/18F/micropurchase/builds/163524948

**Comment by harrisj** [comment]
So, this is a weird one. The issue seems to be something to do with thread variables in Ruby, perhaps exacerbated by Capybara. Let me explain.

We are using the [business_time](https://github.com/bokmann/business_time) gem to do calculations like 5 business days from now. Since we want to not count Federal holidays, the gem allows us to use an initializer to load in the holidays we want to ignore (those are not counted as working days).

``` ruby
Holidays.between(Date.today, 2.years.from_now, :us, :observed).each do
  |holiday| BusinessTime::Config.holidays << holiday[:date]
end
```

However, whenever we get close to a holiday, the business_time gem sometimes seems to treat the holiday as a working day, causing a test to fail. This effect is seemingly random, which is _why_ the test fails, since the controller method we are testing sometimes doesn't treat the holiday as such, but the test assertion we compute independently does.

``` ruby
delivery_date = 5.business_days.after(@end_time)
formatted_delivery_date = DcTimePresenter.format(delivery_date)
 expect(page).to have_content(
    "Estimated delivery date #{formatted_delivery_date}"
  )
```

This is from the failing Cucumber step. This feature is testing the code that shows an "estimated delivery deadline" for an auction on the edit form. This code calls the [business_days_controller](https://github.com/18F/micropurchase/blob/develop/app/controllers/api/v0/business_days_controller.rb) backend with a date and time like `'2016-11-05'`, `'1:00 PM'` and the controller returns a JSON string with the estimated deadline.

After doing some digging, I ruled out that the controller was not being initialized or there was some weird float point rounding errors to blame. Finally, as a lark I just added some code to the business_days controller to do this:

``` ruby
  def show
    real_days = params[:day_count].to_i
    puts "TIME STR #{params[:date]} #{params[:time]} #{real_days}"
    time = DcTimePresenter.parse("#{params[:date]} #{params[:time]}")
    datetime = nil

    puts "BIZDAY IN: #{time.inspect}"

    100.times do
      datetime = DefaultDeadlineDateTime.new(start_time: time, day_offset: real_days).dc_time
      puts "BIZDAY_OUT: #{DcTimePresenter.format(datetime)}"
    end

    render json: { date: DcTimePresenter.format(datetime) }
  end
```

This is running the offset calculation 100 times and printing it out to stdout. `DefaultDeadlineDateTime` is just a wrapper around BusinessTime's day offset calculation. And in the output I saw that sometimes it would be the correct value of `11/16/2016` for the test and sometimes `11/15/2016` for the test. I added some code to print out the biz days it uses as part of the lookup as well as the size of the `Config.holidays` array and noticed something interesting

```
5 > 8 9 10 14 15 | main 40
BIZDAY_OUT: November 16, 2016 01:00:00 PM EST
5 > 8 9 10 11 14 | main 0
BIZDAY_OUT: November 15, 2016 01:00:00 PM EST
```

To translate this, on some calculations it was able to load its `Config.holidays` and that included Veteran's Day (11/11/2016), while on some other calculations, it didn't know anything about the holidays. These were two calculations run in sequence in the same method. WTF?

A few printfs later, I traced the issue to its source. The config is not being cleared in some cases, it's just not being found. To be threadsafe, `business_time`  stores its config in the main thread's storage. If it can't find the config (ie, when you reference it the first time), it'll initialize with a default hash

```ruby
module BusinessTime
  class Config
    DEFAULT_CONFIG = {
      holidays:              [],
      beginning_of_workday:  '9:00 am',
      end_of_workday:        '5:00 pm',
      work_week:             %w(mon tue wed thu fri),
      work_hours:            {},
      work_hours_total:      {},
      _weekdays:             nil,
    }

    class << self
      private

      def config
        return local_config if local_config?
        Thread.main[:business_time_config] ||= default_config
      end

      # ... other code ...
     end
  end
end
```

I know it's private, but a call to `Config.holidays` is actually a call to `Config.config['holidays']` in an accessor method further down. After adding some more strategic `puts`, I figured out that in the cases where `Config.holidays` is returning an empty array it's because the `||= default_config` is being triggered, because in some cases the `Thread.main[:business_time_config]` is returning `nil`. Note that this doesn't seem consistent. It will often return the actual config (with holidays that were added by my initializer) in the next call, so it's not just serving up the default_config once it fails. What is going on here?

One possible wrinkle: These are in Cucumber features that use Capybara. As far as I know thus far, I think Capybara runs the Rails app in a subthread to do its integration tests. So when `business_time` is setting the config on `Thread.main` that is actually the thread of the Rake task running my Cucumber specs. It's possible each feature might be run randomly or in different threads, but this error is happening for sequential calls within a single controller method, all of which should be run in the same thread.

**Comment by harrisj** [comment]
The issue seems to be related to Poltergeist, which is the driver for JS. Since this is turning into a rabbit hole, I decided to add an override for Cucumber that just stores the config on the class itself. And I load the holidays as part of the initializer.

```
module BusinessTime
  class Config
    class << self
      def config
        @_config ||= default_config
      end
    end
  end
end

Holidays.between(Date.today, 2.years.from_now, :us, :observed).each do
  |holiday| BusinessTime::Config.holidays << holiday[:date]
end
```
