### ISSUE TITLE
Auto-checking for DUNS number

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#382]
As a vendor who is waiting for a DUNS number to complete my profile, I don't want to have to come back to my profile page and manually enter my DUNS number once I finally get it, if its possible for the system to check for me, so there should be a way for the system to check Sam.gov and update my profile when my DUNS number is assigned.

**Comment by harrisj** [comment]
This is what we have right now for the DUNS number check:
* On login or changing the DUNS number field, it will attempt to check SAM.gov to see if the DUNS is valid.
* A rake task that can be run manually to check all invalid DUNS numbers

A few issues to be resolved that would make this process a bit smoother:
* Right now, we don't logout users ever, so the login check isn't happening. It would be good to add an expiration interval ([I think this parameter is an idleness window](http://apidock.com/rails/ActionController/Base)). We could also explore some way of forcibly logging everybody out perhaps by changing the secret.
* The rake task could be put on a cron, but it might be necessary to flag some accounts as ones to stop checking and figure out when they should be moved to that, since there is a rather low limit to the SAM checking API and enough bogus accounts would deactivate all checking by wasting rate limits on every check.
