### ISSUE TITLE
Admin gives authority to publish auctions over $3500

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#411]
As an admin user, I want to give some admins authority to publish auctions with a start price over $3500, so that we can satisfy a requirement to have a contracting officer sign off on auctions with a potential award of over $3500

Scenario: I give an admin user permission to act as a contracting officer
Given I am an authenticated admin user
And I have permission to edit existing admin users
When I am on the edit screen for admin user A
And I check the "Contracting Officer" checkbox
And I save my changes
Then admin user A has permission to publish auctions with a start price over $3500

**Comment by harrisj** [comment]
I'm not sure yet if we want to make this a checkbox in the admin interface. Currently we use a file [admins.yml](config/admins.yml) to identify admins by the Github ID. I think @adelevie can speak to why, but perhaps it was so we could avoid having to create records in the database/new admin controller actions. Should we just add a `contracting_officers` table to this file? This would simplify some of the work, but it would also make the COs part of the public record (since this repo is public). Is that a dealbreaker for that approach?

**Comment by harrisj** [comment]
Also, is this issue saying that COs can delegate the approval/creation of >$3500 auctions to other administrators that are not COs? Is that allowed? Did you want this or the option for COs to approve $>3500 auctions?

**Comment by adelevie** [comment]
I think this issue likely necessitates a more robust roles system. It might initially be as simple as an additional list in admins.yml.

**Comment by jessieay** [comment]
doing a `boolean` field for `contracting officer` on `User` would be The Easiest Thing. But if we want several roles, perhaps a `roles` habtm relation with `User` would be more robust.

re: admin interface -- is there a reason we aren't using Rails Admin / Active Admin /  Administrate? e

**Comment by mtorres253** [comment]
We can talk about this in grooming. Dave and I talked about this being a good time to start to scale the user setup and management on behalf of admin users. If we want to stick with the existing method, that could be OK.

**Comment by jessieay** [comment]
Since I missed part of grooming I am not 100% sure what the outcome on the "how to deal with contracting officers" convo was. 

We cool with implementing a `roles` table? Seems like users will probably have and belong to many `roles` since an `admin` could also be a `contracting officer` -- having this relationship set up in the DB would also allow us to move away from our current "add yourself to a yml file to be an admin" setup.

Just my 2 cents!

This is just thinking on how to set up the roles. Not sure how exactly we'd ensure that contracting officers "have permission to approve auction payments over $3500" but that could come after.

**Comment by jessieay** [comment]
"I can approve an auction payment" == "I can create an auction"

**Comment by jessieay** [comment]
PR: https://github.com/18F/micropurchase/pull/510

**Comment by mtorres253** [comment]
I changed the requirements a little bit as there is still a small user interaction here. I think it's already done, just wanted to take out the part about permissions as it's covered in another story
