### ISSUE TITLE
System shows pending message when DUNS number is being verified with Sam.gov

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#426]
As a registered vendor, I want to know the status of my profile while it is being validated, so I should see a pending message while my profile is being validated

Scenario: System shows pending message while vendor DUNS number is being checked in Sam.gov
Given that I am a registered vendor
And I have entered a DUNS number in my profile
And the system is checking Sam.gov to verify my DUNS number
When I go to my profile page
Then I should see a message on my profile page "Your profile is pending while your DUNS number is being validated. This typically takes less than one hour" 

Note: Check with Alan to make sure the estimate is accurate

**Comment by harrisj** [comment]
So, it seems like we have two ways of handling this, both of which would involve some DB alteration:

1. Change the sam_account column from a boolean to something like `sam_status` that is either `new`, `pending` or `found` (I guess we could have an option for explicitly rejecting too)
2. Add a `sam_checked` datetime column. If it's nil that means it's never been checked, otherwise it's the time of the last check for that user.

We could also of course do both if we think that makes sense. Thoughts?

**Comment by jessieay** [comment]
@harrisj I like the idea of doing a `datetime` column. That also serves as a `true` / `false` checker for whether something has been checked against sam. We wouldn't have pending, but assuming this is running in a delayed job that is kicked off as soon as someone enters their same acct number, these things would not be pending for long anyway.

**Comment by adelevie** [comment]
I like the proposal. Let's think through the statuses:

- `new`. this is the default. The DUNS has never been validated by SAM.gov. (alias/display name could be `pending`--conceptually they seem the same to me)
- `accepted`. SAM.gov accepts the DUNS.
- `rejected`. SAM.gov rejects the DUNS.

`sam_checked` is great. Ideally we should run these against all DUNS numbers fairly regularly. Someone could who was once accepted could become rejected and we want to catch that.

**Comment by harrisj** [comment]
Three more questions then:

1. Did you want a nil state in addition to the other states? Or should we have `new, pending, accepted, rejected`?
2. Does SAM.gov API actually ever reject a DUNS number or is this something we would apply if the DUNS has not been accepted and it's been a long enough time?
3. We should probably change `sam_checked` to `sam_last_checked` to make it more clear it's a datetime.

**Comment by jessieay** [comment]
PR for this here 

https://github.com/18F/micropurchase/pull/467

Didn't end up adding the timestamp for `duns_last_checked` because I couldn't figure out where we'd need it. We have logic in `SamAccountReckoner` now that sees if the DUNS number has changed and updates the status to `pending` if it has.
