### ISSUE TITLE
Include winning bidder in public and private REST API responses

### ISSUE THREAD

**Issue by adelevie** [18F/micropurchase#453]
As a consumer of the Micropurchase API, I want to know who the winner of a given auction is and I don't want to have to munge data or have to interpret the API response to see who won. So, when an auction has ended, and I make a request to get information for that auction, the winner of that auction should be easily identifiable in the response.

Scenario: Auction data is requested after winner is identified
Given that there is an auction where a winner has been identified
When a GET request is made for that auction data
Then the response should identify the winner of that auction
And the winner should be easy to identify (front-end consumer should not have to 'figure anything out')

Responding to @gemfarmer's need to know who the winner is given the auctions.json data. It would be redundant to have to recalculate that in JS, so we should just ensure the API returns it.

**Comment by mtorres253** [comment]
@adelevie @gemfarmer Can you be more specific as to why this data is being used? Do we need anything specific returned?

**Comment by gemfarmer** [comment]
@mtorres253 I'll take a stab.

#### User stories:

_As a front end developer_ on this project I want to be able to know who won an auction, when they won it, and how much they won it for in order to present this information on the [previous winners dashboard](micropurchase.18f.gov/auctions/winners/).

_As someone interested in collecting data_ about the micropurchase platform, I want to be able to know who won an auction, when they won it, and how much they won it for in order to better understand the micropurchase platform.

Why this is useful for the dashboard
- *Accuracy/consistency*: the dashboard does quite a bit of data munging/transforms to determine the "winning bid" and "winning bidder" for a particular auction. Currently, given the `auctions/` api endpoint, the winner is unclear and therefore open to misinterpretation (e.g. is the winner the last bidder? Is it the lowest bidder? ). 
- *Redundancy*: it doesn't make sense to be performing these data transform in back-end AND front-end
- *Performance*: less munging = charts show up faster

**Comment by adelevie** [comment]
As for points, this feels like a 2 or a 3. We already have the API setup and [the methods](https://github.com/18F/micropurchase/blob/develop/app/models/presenter/auction.rb#L103-L105) for calculating the winners. We just need to connect the two.

**Comment by mtorres253** [comment]
Perfect @gemfarmer. I updated the story. And, I pointed it as a 3 based on @adelevie. Since there are no users yet for the dashboard, this is not an urgent priority. However, we should be returning the winner in the response as it is one of the more important data points.

**Comment by vzvenyach** [comment]
FWIW, I have an javascript library that allows for easy client-side determination of the winning bid. https://github.com/18F/micropurchasedata

It is available as a library called `auction.min.js` and is as simple as `var a = new Auction(data).getWinningBid();` where `data` is the response from the API.

**Comment by jessieay** [comment]
@vzvenyach once https://github.com/18F/micropurchase/pull/463 is merged you will be able to do this to find the winner for a bid:

```
auction = Auction.last
rules = RulesFactory.new(auction).create
winning_bid = rules.winning_bid
```

**Comment by gemfarmer** [comment]
@jessieay where are you at with this? Will `winning_bid` be an available attribute on the auctions API when #463 is merged?

**Comment by gemfarmer** [comment]
@vzvenyach awesome idea (https://github.com/18F/micropurchasedata). I think I'm going to add to that API and refactor the front end code accordingly. :)

**Comment by jessieay** [comment]
@gemfarmer I just pulled this into current about 30 mins ago. Plan is to add winning_bid to api here (#463 just makes parsing that logic easier) -- do you no longer need this if you're going to use the js lib?

**Comment by gemfarmer** [comment]
@jessieay cool. Preferably it would be an available attribute on the API – no need to do the logic twice. Plus the winning bid in the library is strictly [lowest bid](https://github.com/18F/micropurchasedata/blob/master/lib/Auction.js#L35) which I don't think is wholly accurate (correct me if I'm wrong). I will be using the js library, but mostly to obfuscate calculations that I'm doing on the script level

**Comment by jessieay** [comment]
via Slack, requested attrs for winning bid are:

* amount
* bidder id

**Comment by jessieay** [comment]
PR : https://github.com/18F/micropurchase/pull/484
