### ISSUE TITLE
Bids are recorded by method

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#559]
As an micropurchase team member, I want to know whether a bid was made via API or manually, so that I know where to focus my energy in terms of development time, so the system should tell me that

Scenario: A bid is made via API
Given that there is an auction
Given that there is a registered vendor that has bid via API on that auction
When the system receives the bid
Then the the system should store some indication that the bid was made via API

Scenario: A bid is made manually
Given that there is an auction
Given that there is a registered vendor that has bid manually on that auction (actually clicked the bid button and manually recorded their bid)
When the system receives the bid
Then the the system should store some indication that the bid was made manually

Note: this is tied to pull request #557. Let's discuss in planning

**Comment by harrisj** [comment]
Thank you for correcting my work putting the cart in front of the horse. Sorry for going out of order here. I would like to know if we can avoid user stories for this functionality since this does not actually affect anything the user sees. I added some logic at the controller tests for regular web requests and API requests instead.

**Comment by harrisj** [comment]
Fixed in PR #557
