### ISSUE TITLE
Update UI/UX based on mockups

### ISSUE THREAD

**Issue by blacktm** [18F/micropurchase#60]
Current mockups here – post a comment if you have feedback on them:

![mockups](https://cloud.githubusercontent.com/assets/887429/10732871/8f9977ca-7bd2-11e5-91ff-ee6f78fa6486.png)

**Comment by awfrancisco** [comment]
Here are my edits:

Heading/titles should be sentence case. So it should be:
Getting started
Complete your account
Confirm details
Issues open for bid
Bid submitted (also a typo in that one)
My bids
Current bid

Probably should change “the shit you’re doing” but I’ll leave that one up to you all. 

On page G, I’d change it to:
“If your bid is selected as the winner, we will contact you with further instructions."

**Comment by blacktm** [comment]
@awfrancisco Thanks for the feedback! Didn't know about the heading/title capitalization (maybe I should read the [content guide](https://pages.18f.gov/content-guide/capitalization/). And whoops, that was a placeholder – I should watch my :hankey: language.

**Comment by adelevie** [comment]
@blacktm anything left to fix here?

**Comment by ddotrollins** [comment]
Updated mockups with changes to the user flow and some layout changes.  Key things to note are:
- Forcing users to login in order to place a bid. They can view a project in the listing and detail view but the 'Bid' button is 'inactive' until the user logs in.
- Updated user bidding flow (User places bid on listing or detail view and then confirms the amount)
- Adding in additional UI elements on Open Projects View
- Updated Footer and Header UI with additional Nav links
- Added in link to Policies and Guidelines (if we need this)
- Updated Project Detail view
- Added in responsive considerations for Project listing component
- Added in tagging system

Reach out with any questions.
[micopurchasing-mockups v2.pdf](https://github.com/18F/micropurchase/files/36083/micopurchasing-mockups.v2.pdf)
<img width="1194" alt="screen shot 2015-11-16 at 6 11 55 pm" src="https://cloud.githubusercontent.com/assets/9273855/11197796/d2909132-8c8d-11e5-998d-a35fba9c4c3b.png">

**Comment by adelevie** [comment]
@ddotrollins, this is great!

**Comment by ddotrollins** [comment]
Updated mockups based on conversations from today.
[micopurchasing-mockups v3.pdf](https://github.com/18F/micropurchase/files/37265/micopurchasing-mockups.v3.pdf)
<img width="994" alt="screen shot 2015-11-17 at 5 05 40 pm" src="https://cloud.githubusercontent.com/assets/9273855/11226451/fdd127ce-8d4d-11e5-8a77-145f6c69acc6.png">

**Comment by ddotrollins** [comment]
Updated wires to reflect changes outlines in Sprint Planning Meeting. Updates show:
- New bid flow. After bid amount is confirmed, user moves back to bid detail page with updated alert.
- Bid Error Alerts. If a user attempts to bid an amount equal or greater than the current bid amount, user receives an error alert on that page (either the Home or Project Detail page).
- Added note to the "Completed By" field on the Bid Detail page. When a project is closed, if we decide to show names, we can have the "Completed By" field shown in the right rail component. Otherwise, remove.

[micopurchasing-mockups v4.pdf](https://github.com/18F/micropurchase/files/42172/micopurchasing-mockups.v4.pdf)

<img width="692" alt="screen shot 2015-11-23 at 5 54 27 pm" src="https://cloud.githubusercontent.com/assets/9273855/11352716/fae11318-920b-11e5-9541-5f21e5dc476e.png">

**Comment by ddotrollins** [comment]
Updated wireframes.
[micropurchasing-mockups v5.pdf](https://github.com/18F/micropurchase/files/50098/micropurchasing-mockups.v5.pdf)

Updated Landing page.
![m - landing page](https://cloud.githubusercontent.com/assets/9273855/11541267/4e158d44-98ff-11e5-83e6-db3b0a271954.png)

**Comment by vzvenyach** [comment]
:+1:

**Comment by ddotrollins** [comment]
[micropurchasing-mockups v5.pdf](https://github.com/18F/micropurchase/files/73551/micropurchasing-mockups.v5.pdf)

**Comment by blacktm** [comment]
This is looking really good. Nice work @ddotrollins

**Comment by adelevie** [comment]
Hey Tom! Long time no talk!

**Comment by ddotrollins** [comment]
Early 2016 wireframes [Micropurchase.pdf](https://github.com/18F/micropurchase/files/258071/Micropurchase.pdf)
