### ISSUE TITLE
Unexpected error when trying to save updates to an existing auction

### ISSUE THREAD

**Issue by mtorres253** [18F/micropurchase#736]
To duplicate:

Navigate to https://micropurchase.18f.gov/admin/auctions/24/edit
Change the auction status to "Rejected"
Enter this value in the delivery URL field: https://github.com/18F/aws-broker/pull/5
Click "Update" button

Expected behavior: Changes are saved
Actual behavior: Changes are not saved, and I get a "User can't be blank" error
<img width="1277" alt="screen shot 2016-06-20 at 11 40 16 am" src="https://cloud.githubusercontent.com/assets/100149/16206225/3bef7fbe-36dc-11e6-91c5-3cbd77419ce1.png">

**Comment by jessieay** [comment]
I know what this is about! We set the `user` on an `auction` on create, but on update we do not change so that in the case that someone who is not the creator updates an auction, we don't lose that info. eg: contracting officer creates an auction but someone else updates...we still want this auction to "belong to" the contracting officer.

fix would be to update the `user` for an auction to the current_user if it is not assigned. probably in `UpdateUser` service class

**Comment by harrisj** [comment]
I haven't started this yet and probably won't get ot it tonight if you want to take it

**Comment by jessieay** [comment]
PR : https://github.com/18F/micropurchase/pull/767
